title = "Sift"
gitSourceBranch = "main"
changelog = true

classOrder = ["Sift"]

[home]
# enabled = true
includeReadme = true

[[navbar.items]]
label = "Itch.io"
href = "https://csqrl.itch.io/sift"
position = "right"

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"
